// Tela 6 — Finalização do pedido (nome + código de retirada)
function ScreenConfirm() {
  const STATES = { FORM: "form", DONE: "done" };
  // Show the "done" state in the static mock — most visually rich and the most informative for handoff.
  const state = STATES.DONE;
  return (
    <div className="screen" data-screen-label="06 Finalização">
      <AppHeader cartCount={0}/>

      <section className="container" style={{ paddingTop: 32, paddingBottom: 56 }}>
        {state === STATES.FORM ? <FormState/> : <DoneState/>}
      </section>

      <AppFooter/>
    </div>
  );
}

function FormState() {
  return (
    <div style={{ display: "grid", gridTemplateColumns: "1fr 380px", gap: 32, alignItems: "flex-start", maxWidth: 1120, margin: "0 auto" }}>
      <div>
        <h1 style={{ fontFamily: "var(--font-display)", fontSize: 36, fontWeight: 800, color: "var(--ink-800)", letterSpacing: "-0.03em", lineHeight: 1 }}>
          Falta só seu nome
        </h1>
        <p style={{ fontSize: 15, color: "var(--fg-2)", marginTop: 8 }}>
          A gente usa só pra gerar o código que você apresenta no balcão na hora de retirar.
        </p>
        <div className="card" style={{ padding: 28, marginTop: 24 }}>
          <label style={{ fontSize: 13, fontWeight: 700, color: "var(--ink-700)", letterSpacing: "0.04em", textTransform: "uppercase" }}>Seu nome</label>
          <input
            defaultValue="Marina"
            style={{
              display: "block", width: "100%", boxSizing: "border-box",
              background: "var(--bg-surface)",
              border: "1.5px solid var(--tomate-500)",
              borderRadius: "var(--r-sm)",
              padding: "14px 16px", marginTop: 10,
              fontFamily: "var(--font-body)", fontSize: 16, fontWeight: 500,
              color: "var(--ink-800)", outline: "none",
              boxShadow: "0 0 0 3px var(--tomate-50)"
            }}
          />
        </div>
      </div>
      <aside>
        <div className="card" style={{ padding: 24 }}>
          <h3 style={{ fontFamily: "var(--font-display)", fontSize: 18, fontWeight: 700 }}>Total</h3>
          <div className="price" style={{ fontSize: 28, fontWeight: 700, color: "var(--ink-800)", marginTop: 4 }}>R$ 51,84</div>
          <button className="btn btn-primary btn-block" style={{ marginTop: 18 }}>Confirmar pedido</button>
        </div>
      </aside>
    </div>
  );
}

function QrCodePattern({ seed = "MA-7K2D", size = 232 }) {
  // Decorative QR-like pattern. Real QR will be generated by the backend at handoff.
  const N = 25;
  const cell = size / N;
  // Seeded pseudo-random so the pattern is stable across renders.
  let h = 0;
  for (let i = 0; i < seed.length; i++) h = (h * 31 + seed.charCodeAt(i)) >>> 0;
  const rnd = () => { h = (h * 1664525 + 1013904223) >>> 0; return h / 0xffffffff; };
  const inFinder = (x, y) => (
    (x < 7 && y < 7) || (x >= N - 7 && y < 7) || (x < 7 && y >= N - 7)
  );
  const dots = [];
  for (let y = 0; y < N; y++) {
    for (let x = 0; x < N; x++) {
      if (inFinder(x, y)) continue;
      // Logo cutout (center 7x7)
      if (x >= 9 && x <= 15 && y >= 9 && y <= 15) continue;
      if (rnd() > 0.5) dots.push([x, y]);
    }
  }
  const Finder = ({ cx, cy }) => (
    <g>
      <rect x={cx * cell} y={cy * cell} width={7 * cell} height={7 * cell} rx={cell * 1.6} fill="#1c1a16"/>
      <rect x={(cx + 1) * cell} y={(cy + 1) * cell} width={5 * cell} height={5 * cell} rx={cell * 1.1} fill="#fff"/>
      <rect x={(cx + 2) * cell} y={(cy + 2) * cell} width={3 * cell} height={3 * cell} rx={cell * 0.6} fill="#1c1a16"/>
    </g>
  );
  return (
    <svg width={size} height={size} viewBox={`0 0 ${size} ${size}`} aria-label="QR code do pedido MA-7K2D" style={{ display: "block" }}>
      <rect width={size} height={size} fill="#fff" rx={cell * 1.5}/>
      {dots.map(([x, y], i) => (
        <rect key={i} x={x * cell + cell * 0.08} y={y * cell + cell * 0.08} width={cell * 0.84} height={cell * 0.84} rx={cell * 0.18} fill="#1c1a16"/>
      ))}
      <Finder cx={0} cy={0}/>
      <Finder cx={N - 7} cy={0}/>
      <Finder cx={0} cy={N - 7}/>
      {/* Center brand mark */}
      <g transform={`translate(${size / 2}, ${size / 2})`}>
        <circle r={cell * 4.6} fill="#fff"/>
        <circle r={cell * 3.6} fill="var(--tomate-500)"/>
        <text textAnchor="middle" dominantBaseline="central" y={cell * 0.2}
              style={{ fontFamily: "var(--font-display)", fontWeight: 800, fontSize: cell * 4.2, fill: "#fff", letterSpacing: "-0.04em" }}>m</text>
      </g>
    </svg>
  );
}

function DoneState() {
  return (
    <div style={{ maxWidth: 1120, margin: "0 auto" }}>
      <div style={{ display: "grid", gridTemplateColumns: "1.2fr 1fr", gap: 32, alignItems: "stretch" }}>

        {/* Big code card */}
        <div style={{
          background: "var(--ink-800)", color: "#fff",
          borderRadius: "var(--r-xl)", padding: "40px 44px",
          position: "relative", overflow: "hidden",
          boxShadow: "var(--shadow-3)",
          display: "flex", flexDirection: "column"
        }}>
          <div style={{ display: "flex", alignItems: "center", gap: 12 }}>
            <div style={{ width: 44, height: 44, borderRadius: "50%", background: "var(--folha-500)", display: "grid", placeItems: "center", flexShrink: 0 }}>
              <Icon name="check" size={24} color="#fff" strokeWidth={3}/>
            </div>
            <div>
              <div className="eyebrow" style={{ color: "var(--manga-300)" }}>Pedido confirmado</div>
              <div style={{ fontFamily: "var(--font-display)", fontSize: 24, fontWeight: 800, marginTop: 2, letterSpacing: "-0.025em" }}>
                Pode vir buscar, Marina!
              </div>
            </div>
          </div>

          <div style={{ marginTop: 28, display: "grid", gridTemplateColumns: "232px 1fr", gap: 28, alignItems: "center" }}>
            {/* QR */}
            <div style={{ position: "relative", padding: 12, background: "#fff", borderRadius: 18, boxShadow: "0 8px 24px rgba(0,0,0,0.25)" }}>
              <QrCodePattern seed="MA-7K2D" size={208}/>
            </div>

            {/* Code + actions */}
            <div>
              <div style={{ fontSize: 11, fontWeight: 700, letterSpacing: "0.12em", textTransform: "uppercase", color: "var(--ink-300)" }}>
                Mostre o QR no balcão
              </div>
              <div style={{ fontSize: 14, color: "var(--ink-200)", marginTop: 10, lineHeight: 1.5 }}>
                O atendente da Padaria do Zé lê o QR pra liberar seu pedido. Salve essa tela ou tire um print 📸.
              </div>

              <div style={{
                marginTop: 18, padding: "12px 14px",
                background: "rgba(255,255,255,0.06)",
                border: "1px dashed rgba(255,255,255,0.18)",
                borderRadius: "var(--r-sm)",
                display: "flex", justifyContent: "space-between", alignItems: "center", gap: 12
              }}>
                <div>
                  <div style={{ fontSize: 10, fontWeight: 700, color: "var(--ink-400)", letterSpacing: "0.12em", textTransform: "uppercase" }}>
                    Ou diga o código
                  </div>
                  <div style={{
                    fontFamily: "var(--font-mono)", fontSize: 26, fontWeight: 700,
                    letterSpacing: "0.06em", color: "var(--tomate-300)", marginTop: 2, lineHeight: 1
                  }}>
                    MA-7K2D
                  </div>
                </div>
                <button title="Copiar código" style={{
                  background: "transparent", border: "1px solid rgba(255,255,255,0.18)",
                  color: "#fff", borderRadius: 10, padding: "8px 10px", cursor: "pointer",
                  display: "inline-flex", alignItems: "center", gap: 6, fontSize: 12, fontWeight: 600
                }}>
                  <Icon name="copy" size={13}/> Copiar
                </button>
              </div>

              <div style={{ display: "flex", gap: 8, marginTop: 14, flexWrap: "wrap" }}>
                <button className="btn" style={{ background: "var(--tomate-500)", color: "#fff", padding: "11px 16px", fontSize: 13 }}>
                  <Icon name="download" size={13}/> Baixar QR
                </button>
                <button className="btn btn-ghost" style={{ color: "#fff", padding: "11px 14px", fontSize: 13, border: "1px solid rgba(255,255,255,0.18)" }}>
                  <Icon name="share-2" size={13}/> WhatsApp
                </button>
              </div>
            </div>
          </div>

          <div style={{ marginTop: "auto", paddingTop: 36, display: "flex", justifyContent: "space-between", alignItems: "flex-end" }}>
            <div>
              <div style={{ fontSize: 11, fontWeight: 700, color: "var(--ink-400)", letterSpacing: "0.12em", textTransform: "uppercase" }}>Pronto em</div>
              <div style={{ fontFamily: "var(--font-mono)", fontSize: 26, fontWeight: 700, color: "var(--folha-300)", marginTop: 4 }}>~18 min</div>
            </div>
            <div style={{ textAlign: "right" }}>
              <div style={{ fontSize: 11, fontWeight: 700, color: "var(--ink-400)", letterSpacing: "0.12em", textTransform: "uppercase" }}>Pedido</div>
              <div style={{ fontFamily: "var(--font-mono)", fontSize: 16, fontWeight: 600, color: "var(--ink-200)", marginTop: 4 }}>#A8B2C9F1</div>
            </div>
          </div>

          {/* Decorative circles */}
          <div style={{ position: "absolute", right: -80, top: -80, width: 200, height: 200, borderRadius: "50%", background: "rgba(255,255,255,0.04)" }}/>
          <div style={{ position: "absolute", right: -30, top: -30, width: 80, height: 80, borderRadius: "50%", background: "rgba(255,255,255,0.06)" }}/>
        </div>

        {/* Pickup location card */}
        <div style={{ display: "flex", flexDirection: "column", gap: 16 }}>
          <div className="card" style={{ overflow: "hidden", flex: 1, display: "flex", flexDirection: "column" }}>
            <div style={{ height: 168, position: "relative",
              backgroundImage: `linear-gradient(180deg, rgba(28,24,18,0) 60%, rgba(28,24,18,0.8) 100%), url(${U("1509440159596-0249088772ff", 800)})`,
              backgroundSize: "cover", backgroundPosition: "center"
            }}>
              <div style={{ position: "absolute", bottom: 14, left: 16, right: 16, color: "#fff" }}>
                <div style={{ fontFamily: "var(--font-display)", fontSize: 22, fontWeight: 800, letterSpacing: "-0.02em" }}>Padaria do Zé</div>
                <div style={{ fontSize: 13, opacity: 0.9 }}>Vila Madalena</div>
              </div>
              <span style={{ position: "absolute", top: 14, right: 14, background: "var(--folha-500)", color: "#fff", fontSize: 11, fontWeight: 700, padding: "5px 10px", borderRadius: 999, letterSpacing: "0.06em", textTransform: "uppercase" }}>Aberto</span>
            </div>
            <div style={{ padding: "18px 20px", flex: 1, display: "flex", flexDirection: "column", gap: 12 }}>
              <div style={{ display: "flex", gap: 10, alignItems: "flex-start" }}>
                <div style={{ color: "var(--tomate-500)", marginTop: 2 }}><Icon name="map-pin" size={16}/></div>
                <div style={{ fontSize: 14, color: "var(--ink-800)", lineHeight: 1.45 }}>
                  R. Wisard, 348 — Vila Madalena<br/>
                  <span style={{ color: "var(--fg-2)", fontSize: 13 }}>São Paulo · SP · 05434-080</span>
                </div>
              </div>
              <div style={{ display: "flex", gap: 10, alignItems: "center" }}>
                <div style={{ color: "var(--tomate-500)" }}><Icon name="phone" size={16}/></div>
                <span className="price" style={{ fontSize: 14, color: "var(--ink-800)" }}>(11) 2389-0042</span>
              </div>
              <div style={{ display: "flex", gap: 8, marginTop: "auto" }}>
                <button className="btn btn-secondary" style={{ flex: 1, padding: "10px 14px", fontSize: 13 }}>
                  <Icon name="map-pin" size={13}/> Ver rota
                </button>
                <button className="btn btn-secondary" style={{ flex: 1, padding: "10px 14px", fontSize: 13 }}>
                  <Icon name="phone" size={13}/> Ligar
                </button>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* Order summary */}
      <div style={{ marginTop: 24, display: "grid", gridTemplateColumns: "1.2fr 1fr", gap: 32, alignItems: "flex-start" }}>
        <div className="card" style={{ padding: 24 }}>
          <h3 style={{ fontFamily: "var(--font-display)", fontSize: 20, fontWeight: 700, color: "var(--ink-800)", letterSpacing: "-0.02em" }}>O que você pediu</h3>
          <ul style={{ listStyle: "none", padding: 0, margin: "18px 0 0", display: "flex", flexDirection: "column", gap: 14 }}>
            {[
              { qty: 1, name: "Tapioca de queijo coalho", price: "R$ 23,90" },
              { qty: 2, name: "Pão na chapa com manteiga", price: "R$ 13,00" },
              { qty: 1, name: "Café com leite e pão na chapa", price: "R$ 14,90" },
            ].map((it, i) => (
              <li key={i} style={{ display: "flex", alignItems: "flex-start", gap: 12 }}>
                <span style={{ background: "var(--ink-100)", color: "var(--ink-700)", padding: "3px 9px", borderRadius: 6, fontSize: 12, fontFamily: "var(--font-mono)", fontWeight: 700, minWidth: 28, textAlign: "center" }}>{it.qty}×</span>
                <span style={{ flex: 1, fontSize: 14, color: "var(--ink-800)", fontWeight: 500 }}>{it.name}</span>
                <span className="price" style={{ fontSize: 14, color: "var(--ink-700)" }}>{it.price}</span>
              </li>
            ))}
          </ul>
          <hr className="divider"/>
          <div style={{ display: "flex", flexDirection: "column", gap: 8 }}>
            <Row label="Subtotal" value="R$ 64,80"/>
            <Row label="Cupom MANDA20" value="− R$ 12,96" valueColor="var(--tomate-600)" valueWeight={600}/>
            <Row label="Taxa de retirada" value="Grátis" valueColor="var(--folha-600)" valueWeight={600}/>
          </div>
          <hr className="divider"/>
          <div style={{ display: "flex", justifyContent: "space-between", alignItems: "baseline" }}>
            <span style={{ fontFamily: "var(--font-display)", fontSize: 17, fontWeight: 700, color: "var(--ink-800)" }}>Total a pagar no balcão</span>
            <span className="price" style={{ fontSize: 24, fontWeight: 700, color: "var(--ink-800)" }}>R$ 51,84</span>
          </div>
        </div>

        <aside style={{ display: "flex", flexDirection: "column", gap: 16 }}>
          <div className="card" style={{ padding: 20 }}>
            <h4 style={{ fontFamily: "var(--font-display)", fontSize: 16, fontWeight: 700, color: "var(--ink-800)", marginBottom: 14 }}>Como funciona a retirada</h4>
            <ol style={{ listStyle: "none", padding: 0, margin: 0, display: "flex", flexDirection: "column", gap: 14, counterReset: "step" }}>
              {[
                "Cai pra Vila Madalena no horário previsto.",
                "Mostra o QR (ou diz o código MA-7K2D) no balcão.",
                "Paga direto com o restaurante (Pix, cartão ou dinheiro).",
                "Pega o rango e tchau!",
              ].map((step, i) => (
                <li key={i} style={{ display: "flex", gap: 12, fontSize: 13, color: "var(--ink-700)", lineHeight: 1.45 }}>
                  <span style={{
                    width: 24, height: 24, borderRadius: "50%",
                    background: "var(--tomate-50)", color: "var(--tomate-600)",
                    fontFamily: "var(--font-mono)", fontWeight: 700, fontSize: 12,
                    display: "grid", placeItems: "center", flexShrink: 0
                  }}>{i + 1}</span>
                  <span>{step}</span>
                </li>
              ))}
            </ol>
          </div>
          <div style={{ display: "flex", gap: 10 }}>
            <button className="btn btn-primary" style={{ flex: 1, padding: "14px 18px", fontSize: 14 }}>
              Fazer outro pedido
            </button>
          </div>
        </aside>
      </div>
    </div>
  );
}

window.ScreenConfirm = ScreenConfirm;
